theme: jekyll-theme-slate
title: 
  <img src="https://user-images.githubusercontent.com/69354578/216736998-02946def-22c0-48ff-9fc6-23416ca10ba8.png" width="100%" align="center">
  <a href="https://gravelrobotics.github.io/" target="_blank" rel="noopener noreferrer">
    <img src="https://user-images.githubusercontent.com/69354578/215622871-eb96834a-cd47-4638-996f-3b8ae9523e4d.png" height="55" align="left">
  </a>
  <a href="https://linkedin.com/in/sohipatel" target="_blank" rel="noopener noreferrer">
    <img src="https://user-images.githubusercontent.com/69354578/215395215-69a65eab-d35e-4986-a3fc-5a507bcf282c.png" height="55" align="right">
  </a>
  <a href="https://www.twitter.com" target="_blank" rel="noopener noreferrer">
    <img src="https://user-images.githubusercontent.com/69354578/215394588-38c0cdb1-bc66-4bdc-9137-60c82627be9c.png" height="55" align="right">
  </a>
  <br>
